// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czirbcdusdzsgibvbqsd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6aXJiY2R1c2R6c2dpYnZicXNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNzkwMDksImV4cCI6MjA2MzY1NTAwOX0.vpoApvhiML8tlGfCzbMQZDWGBA7ZyKL6TVt3LJrRJS0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);